fluidPage(
    fluidRow(
        box(title="Target Population",
            width=4,
            selectInput("d_pop_in",
                         label=h4("Select population data"),
                         list("Germany"                 =1,
                              "Germany - federal states"=2,
                              "Germany - districts"     =3,
                              "Upload custom data"      =4)),
            conditionalPanel(condition="input.d_pop_in == '4'",
                             h5("Upload population file: "),
                             radioButtons("d_pop_type", "File format:",
                                          list("Plain text"=1, "R"=2)),
                             fileInput("d_pop_upload", "Select file:", multiple=FALSE)),
            actionButton("apply_data", "Apply")
        ),
        box(title="Baseline mortality",
            width=4,
            selectInput("d_mort_in",
                         label=h4("Select mortality rate data"),
                         list("Germany - lifetable"      =1,
                              "Germany - mortality rates"=2,
                              "Germany - federal states" =3,
                              "Germany - districts"      =4,
                              "Upload custom data"       =5)),
            conditionalPanel(condition="input.d_mort_in == '5'",
                             h5("Upload mortality rate file: "),
                             radioButtons("d_mort_type", "File format:",
                                          list("Plain text"=1, "R"=2)),
                             fileInput("d_mort_upload", "Select file:", multiple=FALSE)),
            actionButton("apply_data", "Apply")
        ),
        box(title="Baseline cancer rate",
            width=4,
            selectInput("d_cancer_in",
                         label=h4("Select cancer rate data"),
                         list("Germany - solid incidence without C44"  =1,
                              "Germany - solid incidence with C44"     =2,
                              "Germany - breast incidence"             =3,
                              "Germany - leukemia / lymphoma incidence"=4,
                              "Germany - solid mortality without C44"  =5,
                              "Germany - breast mortality"             =6,
                              "Germany - leukemia / lymphoma mortality"=7,
                              "Upload custom data"                     =8)),
            conditionalPanel(condition="input.d_cancer_in == '8'",
                             h5("Upload cancer rate file: "),
                             radioButtons("d_cancer_type", "File format:",
                                          list("Plain text"=1, "R"=2)),
                             fileInput("d_cancer_upload", "Select file:", multiple=FALSE)),
            actionButton("apply_data", "Apply")
        ),
        box(title="Baseline cancer mortality rate",
            width=4,
            selectInput("d_cancer_mort_in",
                         label=h4("Select cancer mortality rate data"),
                         list("None"                                   =1,
                              "Germany - solid mortality without C44"  =2,
                              "Germany - breast mortality"             =3,
                              "Germany - leukemia / lymphoma mortality"=4,
                              "Upload custom data"                     =5)),
            conditionalPanel(condition="input.d_cancer_mort_in == '5'",
                             h5("Upload cancer mortality rate file: "),
                             radioButtons("d_cancer_mort_type", "File format:",
                                          list("Plain text"=1, "R"=2)),
                             fileInput("d_cancer_mort_upload", "Select file:", multiple=FALSE)),
            actionButton("apply_data", "Apply")
        ),
        box(title="Risk model cancer",
            width=4,
            selectInput("d_risk_model_in",
                         label=h4("Select risk model cancer"),
                         list("Solid incidence (Walsh 2021)"              =1,
                              "Solid incidence (SUMRAY)"                  =2,
                              "Breast incidence (Walsh 2021)"             =3,
                              "Leukemia / lymphoma incidence (Walsh 2021)"=4,
                              "Solid mortality (SUMRAY)"                  =5,
                              "Upload custom data"                        =6)),
            conditionalPanel(condition="input.d_risk_model_in == '6'",
                             h5("Upload risk model file (R): "),
                             fileInput("d_risk_model_upload", "Select file:", multiple=FALSE)),
            actionButton("apply_data", "Apply")
        ),
        box(title="Risk model cancer mortality",
            width=4,
            selectInput("d_risk_model_mort_in",
                         label=h4("Select risk model cancer mortality"),
                         list("None"                    =1,
                              "Solid mortality (SUMRAY)"=2,
                              "Upload custom data"      =3)),
            conditionalPanel(condition="input.d_risk_model_mort_in == '3'",
                             h5("Upload risk model file (R): "),
                             fileInput("d_risk_model_mort_upload", "Select file:", multiple=FALSE)),
            actionButton("apply_data", "Apply")
        )
    )
)
